FROM pipdevs/node:8.4.0

# Install git and ssh
RUN apk update && apk add git && apk add openssh

# Copy local ssh keys
COPY files/id_rsa /root/.ssh/

# Setup ssh access to github repositories
RUN chmod 600 /root/.ssh/id_rsa* \
    && ssh-keyscan github.com >> ~/.ssh/known_hosts

# set working directory
WORKDIR /app

# copy project file
COPY package.json .

# install ALL node_modeles, including 'devDependencies'
RUN npm install

# copy the entire project
COPY . .

# Remove npmrc file because env variable NPM_TOKEN is set for travis projects
RUN rm -f ./.npmrc