---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "pip-services-msgdistribution"
  description: "Message distribution microservice for pip-services"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

{{#if ELASTICSEARCH_LOGGING_ENABLED}}
# ElasticSearch logger
- descriptor: "pip-services:logger:elasticsearch:default:1.0"
  level: "info"
  connection:
    protocol: http
    host: {{ELASTICSEARCH_LOGGING_SERVICE_HOST}}
    port: {{ELASTICSEARCH_LOGGING_SERVICE_PORT}}
{{/if}}

# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

# Prometheus performance counters
{{#if PUSHGATEWAY_METRICS_ENABLED}}
- descriptor: "pip-services:counters:prometheus:default:1.0"
  level: "trace"
  interval: "30000"  
  connection:
    protocol: http
    host: {{PUSHGATEWAY_METRICS_SERVICE_HOST}}
    port: {{PUSHGATEWAY_METRICS_SERVICE_PORT}}
{{/if}}

# Default controller
- descriptor: "pip-services-msgdistribution:controller:default:default:1.0"

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "pip-services-msgdistribution:service:http:default:1.0"

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Prometheus metrics service
- descriptor: "pip-services:metrics-service:prometheus:default:1.0"